### ISSUE TITLE
Support for shorthand numeric values

### ISSUE THREAD

**Issue by adambuczynski** [atom/language-css#57]
Shorthand for `0.3` which is often used is simply `.3`. However, the language grammar doesn't pick this up properly and doesn't mark the leading `.` as `constant.numeric`:

![image](https://cloud.githubusercontent.com/assets/490562/15802990/cf0b9ebc-2b1b-11e6-8618-651043bde810.png)

**Comment by esdoppio** [comment]
Works fine for me on Atom 1.8.0 and 1.9.3:

![image](https://cloud.githubusercontent.com/assets/18070858/17422549/bc4bec56-5ae5-11e6-943a-9b84dc9c719a.png)

**Comment by 50Wliu** [comment]
Assuming it got fixed somewhere along the way.

**Comment by adambuczynski** [comment]
It's still broken for me in Atom 1.10.0-dev-98fc8db... :(

![image](https://cloud.githubusercontent.com/assets/490562/17422934/d2e224f6-5b0a-11e6-8fa4-d8e402c071a2.png)

**Comment by esdoppio** [comment]
`.css`, you opened the ticket in language-css, so I assumed you're having problems in CSS files.

**Comment by 50Wliu** [comment]
Pretty sure I fixed that bug, maybe it didn't get into 1.10.0 for SCSS.

**Comment by adambuczynski** [comment]
Yeah I think it's still broken in SCSS, @50Wliu are you able to port your fix to `language-sass`?

**Comment by 50Wliu** [comment]
Yeah of course.  Can you file a new issue there?
